### PR TITLE
1124 country selector

### PR DESCRIPTION
**Pull request by redhog**
Connects https://github.com/SkyTruth/pelagos-server/issues/1124

### CODE REVIEW

**Comment by enriquetuya** [comment]
@redhog this looks really promising! A few changes to improve it:

1- Remove the down arrow from the right corner, since it does not looks good.
- Remove the arrow.
- Add text above the input "Type the filters below:"
- When the user click on the input, trigger the dropdown.
  selection_034

2- Make the X attached to the value, right now you have the X button next to the country name. 
selection_033
We would like to display something like this:
selection_035

3- Make the input fill the full width of the widget, right now is not doing so:
selection_034

**Comment by redhog** [comment]
Please clear cache before testing. This is not how the control looks (you're missing a bunch of styles).

**Comment by redhog** [comment]
Added header text

**Comment by enriquetuya** [comment]
@redhog please work on the following changes:
- [ ] Build is still broken for this PR
- [x] We need to have a fixed width, try start selecting countries, you will see that the widgets start expanding until it reaches the right corner. We would like to keep the widget centered by default and have a max width.

selection_052

gif:
ezgif-395711561
- [x] Remove the down arrow from the right corner, since it does not looks good.
  - Remove the arrow.
  - When the user click on the input, trigger the dropdown. 

selection_052
- [ ] The input border is always highlighted in light blue, we need to remove that border highlight.

selection_053

**Comment by redhog** [comment]
The blue border is there when the widget has focus. If you press tab so that focus is switched to one of the dialog buttons it disappears. Note that the border is ALSO blue on hover, so to test this, move your mouse outside the widget. This is standard for all input fields in our current theme. If you want this changed, it should be done theme-wide for all input fields.

**Comment by enriquetuya** [comment]
@redhog without the `down-arrow` key the input highlight does not look that bad.
Some missing changes:
- [ ] Fix build for this PR.
- [ ] Right now the drop-down is displayed with the `onfocus` and `onclick` event, we want it to be triggered only by the on click event. 
  ezgif-3024690812

**Pull request merged**
