### PR TITLE
312 temporal tiling uglification

### PR DESCRIPTION
**Pull request by redhog**
Connects https://github.com/SkyTruth/pelagos-server/issues/1032

### CODE REVIEW

**Comment by geowurster** [comment]
@redhog Can you provide a sample URL for testing locally?

**Comment by andres-arana** [comment]
@redhog, only the `TypedMatrixParser` class got special `withCredentials` treatment? what about the `Ajax` class? that's only used on headers and workspaces?

**Comment by redhog** [comment]
So, nefore you load the header, you don't have the flag, so you can't use the flag to determine if you're going to use withCredentials or not. So for the header, we have to use the other method - try first without, then  with authentication.

**Comment by redhog** [comment]
@geowurster http://localhost:8080/viz?workspace=/workspace/9e203432-a1c5-44a0-a7a4-2f7508f7a44e

You need to be on this branch, and on the world-fishing-827 project.

**Comment by geowurster** [comment]
@redhog I get a `404` for that URL.  I'm running the server through Vagrant, and the [example URL](https://github.com/skytruth/pelagos-client#quick-virtualized-test-server) works.

**Comment by redhog** [comment]
@geowurster Have you made sure the server is running under the world-fishing-827 project?

```
gcloud config list
```

will tell you the default project. Can also be set in gae/settings.py

**Comment by geowurster** [comment]
@redhog 

```
[core]
account = kevin@skytruth.org
disable_usage_reporting = True
project = world-fishing-827
```

**Pull request merged**
